# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: trade.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0btrade.proto\x12\x02pb\x1a\x1fgoogle/protobuf/timestamp.proto\"m\n\x05Trade\x12(\n\x04time\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0e\n\x06symbol\x18\x02 \x01(\t\x12\x0e\n\x06volume\x18\x03 \x01(\x03\x12\r\n\x05price\x18\x04 \x01(\x01\x12\x0b\n\x03\x62uy\x18\x05 \x01(\x08\x62\x06proto3')



_TRADE = DESCRIPTOR.message_types_by_name['Trade']
Trade = _reflection.GeneratedProtocolMessageType('Trade', (_message.Message,), {
  'DESCRIPTOR' : _TRADE,
  '__module__' : 'trade_pb2'
  # @@protoc_insertion_point(class_scope:pb.Trade)
  })
_sym_db.RegisterMessage(Trade)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TRADE._serialized_start=52
  _TRADE._serialized_end=161
# @@protoc_insertion_point(module_scope)
